import { Heart, Landmark, Megaphone, Users } from 'lucide-react'
import { motion } from 'motion/react'
import LowPolyBackdrop from '../components/LowPolyBackdrop'
import ProfitCard from '../components/ProfitCard'
import { siteConfig } from '../config'

const icons = [Heart, Megaphone, Landmark, Users]

export default function Impact() {
  return (
    <section id="impact" className="relative scroll-mt-20 overflow-hidden px-5 py-24 sm:px-8 lg:px-12 lg:py-32">
      <LowPolyBackdrop mood="tunnel" />
      <div className="relative z-10 mx-auto max-w-[1320px]">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.35 }}
          transition={{ duration: 0.75, ease: [0.22, 1, 0.36, 1] }}
          className="grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end"
        >
          <div>
            <p className="section-kicker">WEEKLY PROFIT FLOW</p>
            <h2 className="mt-5 max-w-3xl text-5xl font-medium leading-[.96] tracking-[-.055em] sm:text-6xl lg:text-7xl">The night gives back</h2>
          </div>
          <div className="max-w-xl lg:justify-self-end">
            <p className="text-sm leading-7 text-muted sm:text-base">Every week, profit generated by the Oxmew meme coin and its wider ecosystem follows one clear route</p>
            <p className="mt-4 border-l border-green/50 pl-4 text-xs leading-6 text-white/70">This is a project profit allocation model, not a token supply distribution</p>
          </div>
        </motion.div>

        <div className="mt-12 grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
          {siteConfig.profitFlow.map((item, index) => {
            const Icon = icons[index]
            if (index === 0) {
              return <ProfitCard key={item.label} {...item} index={index} featured icon={<Icon size={21} strokeWidth={1.6} />} />
            }
            return null
          })}
          <div className="grid gap-4">
            {siteConfig.profitFlow.slice(1).map((item, offset) => {
              const index = offset + 1
              const Icon = icons[index]
              return <ProfitCard key={item.label} {...item} index={index} icon={<Icon size={19} strokeWidth={1.6} />} />
            })}
          </div>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.6 }}
          transition={{ duration: 0.7, delay: 0.1, ease: [0.22, 1, 0.36, 1] }}
          className="profit-rail mt-6 overflow-hidden border border-white/10 bg-black/30 p-4 sm:p-5"
        >
          <div className="flex h-2 w-full overflow-hidden" aria-label="Weekly profit allocation visual">
            {siteConfig.profitFlow.map((item) => <span key={item.label} style={{ width: `${item.percentage}%`, backgroundColor: item.accent }} />)}
          </div>
          <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
            {siteConfig.profitFlow.map((item) => (
              <div key={item.shortLabel} className="flex items-center gap-2 text-[9px] tracking-[.16em] text-white/55">
                <span className="h-1.5 w-1.5 rotate-45" style={{ backgroundColor: item.accent }} />
                <span>{item.percentage}% {item.shortLabel.toUpperCase()}</span>
              </div>
            ))}
          </div>
        </motion.div>

        <div className="mt-16 border-y border-white/10 py-7">
          <div className="mb-6 flex items-center gap-4 text-[9px] tracking-[.24em] text-white/40"><span>TOKEN SIGNAL</span><span className="h-px flex-1 bg-white/10" /></div>
          <div className="grid gap-6 sm:grid-cols-3 sm:gap-0">
            {[
              ['TICKER', siteConfig.ticker],
              ['BLOCKCHAIN', siteConfig.blockchain.toUpperCase()],
              ['SUPPLY', siteConfig.supply],
            ].map(([label, value], index) => (
              <div key={label} className={`token-fact ${index > 0 ? 'sm:border-l sm:border-white/10 sm:pl-8' : ''}`}>
                <p className="text-[9px] tracking-[.23em] text-muted">{label}</p>
                <p className="mt-2 text-2xl font-medium tracking-[-.04em] text-white sm:text-3xl">{value}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
